"""Pick one patient study per stage and output .gitignore rules to track them.

Reads the preprocessed CSV, selects a study close to the median slice count
for each stage (train/test), and prints gitignore negation rules for:
  - raw .dcm files (stage_2_train / stage_2_test)
  - preprocessed .png files (1x512x512_-20_107)
"""

import csv
import statistics
import sys
from collections import defaultdict
from pathlib import Path

DATASET = "rsna-intracranial-hemorrhage-detection"
PRE_DIR = "1x512x512_-20_107"
CSV_PATH = Path(f"datasets/pre/{DATASET}/df.csv")

RAW_STAGE_DIR = {"train": "stage_2_train", "test": "stage_2_test"}


def load_studies(csv_path: Path) -> dict[str, list[dict]]:
    """Group rows by (stage, StudyInstanceUID)."""
    studies: dict[tuple[str, str], list[dict]] = defaultdict(list)
    with open(csv_path) as f:
        for row in csv.DictReader(f):
            key = (row["stage"], row["StudyInstanceUID"])
            studies[key].append(row)
    return studies


def pick_study(
    studies: dict[tuple[str, str], list[dict]], stage: str
) -> tuple[str, list[dict]]:
    """Pick the study closest to median size for a given stage."""
    stage_studies = {k: v for k, v in studies.items() if k[0] == stage}
    median_size = int(statistics.median(len(v) for v in stage_studies.values()))
    # Pick the first study matching median size (deterministic via sorted keys)
    for key in sorted(stage_studies):
        if len(stage_studies[key]) == median_size:
            rows = sorted(stage_studies[key], key=lambda r: int(r["order"]))
            return key[1], rows
    # Fallback: closest to median
    key = min(stage_studies, key=lambda k: abs(len(stage_studies[k]) - median_size))
    rows = sorted(stage_studies[key], key=lambda r: int(r["order"]))
    return key[1], rows


def main() -> None:
    if not CSV_PATH.exists():
        print(f"Error: {CSV_PATH} not found", file=sys.stderr)
        sys.exit(1)

    studies = load_studies(CSV_PATH)
    base = f"datasets"

    lines = [
        "# Sample patient studies (one per stage, auto-generated by scripts/pick_sample_patient.py)"
    ]

    for stage in ("train", "test"):
        study_uid, rows = pick_study(studies, stage)
        patient_id = rows[0]["PatientID"]
        raw_dir = RAW_STAGE_DIR[stage]

        lines.append(
            f"# {stage}: PatientID={patient_id}, StudyInstanceUID={study_uid} ({len(rows)} slices)"
        )

        for row in rows:
            sop = row["SOPInstanceUID"]
            lines.append(
                f"!{base}/raw/{DATASET}/{raw_dir}/{sop}.dcm"
            )
            lines.append(
                f"!{base}/pre/{DATASET}/{PRE_DIR}/{sop}.png"
            )

    print("\n".join(lines))


if __name__ == "__main__":
    main()
